##################################################
# Name: pulumi_update.yaml
# Description: Runs pulumi update on pushes to environment branches
##################################################

name: Pulumi update

on:

  push:
    branches:
      - environment/development
      - environment/staging
      - environment/master

env:

  # Pulumi Secrets
  PULUMI_ACCESS_TOKEN: ${{ secrets.PAT_PULUMI }}
  COMMENT_ON_PR: 0 # Enable if not using the Pulumi GitHub App
  PULUMI_ROOT: infra

  # GitHub Secrets
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # AWS Secrets
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: "ap-east-1"

  # Azure Secrets
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ENVIRONMENT: "public"
  ARM_LOCATION: "australiaeast"

  # GCP Secrets
  GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_REGION: "australia-southeast-1"
  GOOGLE_ZONE: "australia-southeast-1"

  # Kubernetes
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:

  pulumi_update:

    name: Run Pulumi update

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30
    continue-on-error: false

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:

      - id: checkout_repository
        name: Checkout repository
        uses: actions/checkout@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          persist-credentials: true
          fetch-depth: 1

      - id: pulumi_update
        name: Pulumi update
        uses: docker://docker.io/pulumi/actions:latest
        env:
          PULUMI_CI: pr
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        with:
          args: update --yes
